version: '3.9'
services:
  db:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - ./docker/postgres.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres-data:
